### ISSUE TITLE
All resources are unable to download, 403 error.

### ISSUE THREAD

**Issue by UCHIHAHA103** [SimpleSandman/UmaMusumeToolbox#2]
It seems that this link cannot be opened.
https://prd-storage-umamusume.akamaized.net/dl/resources/
![image](https://github.com/SimpleSandman/UmaMusumeToolbox/assets/61904674/07f54fef-f942-4b26-980f-ff2ec0739186)

![Snipaste_2024-03-17_19-17-58](https://github.com/SimpleSandman/UmaMusumeToolbox/assets/61904674/0e94a478-487c-43ec-84c2-82085f7cf966)
![Snipaste_2024-03-17_19-18-15](https://github.com/SimpleSandman/UmaMusumeToolbox/assets/61904674/2038af36-4796-44b9-990a-52ffeb6502fc)

**Comment by SimpleSandman** [comment]
One serious requirement is the use of a VPN to Japan. Just like when you're trying to play the game itself.

Now, when I was running a complete download without any existing files, I ran into some files that caused a 403 (forbidden) error. Which nearly all of them were resolved by re-running the program after it completed the first time.

Below are some possible solutions for you:

```
========== POSSIBLE WORKAROUNDS ==========

NOTE: This could be due to a 403 (forbidden) error killing the connection/download too early.
- When this program has finished downloading, restart this program with "SkipExistingFiles": true in the "appsettings.json" config file so you can simply download the missing files that received this error.
- You can manually download this particular file by pasting the URL into your browser.
- You can also also validate this with an API platform like "Postman" with the URL posted above the error message.

==========================================
```

**Comment by UCHIHAHA103** [comment]
> One serious requirement is the use of a VPN to Japan. Just like when you're trying to play the game itself.
> 
> Now, when I was running a complete download without any existing files, I ran into some files that caused a 403 (forbidden) error. Which nearly all of them were resolved by re-running the program after it completed the first time.
> 
> Below are some possible solutions for you:
> 
> ```
> ========== POSSIBLE WORKAROUNDS ==========
> 
> NOTE: This could be due to a 403 (forbidden) error killing the connection/download too early.
> - When this program has finished downloading, restart this program with "SkipExistingFiles": true in the "appsettings.json" config file so you can simply download the missing files that received this error.
> - You can manually download this particular file by pasting the URL into your browser.
> - You can also also validate this with an API platform like "Postman" with the URL posted above the error message.
> 
> ==========================================
> ```

Thanks a lot！i have solve it with the vpn
